### ISSUE TITLE
Pardon, assemble the book

### ISSUE THREAD

**Issue by cross-hello** [pkivolowitz/asm_book#11]
Just like C is most higher level of assembly language, now it may will be appreciated if could get a higher level of documentation format - pdf.

**Comment by pkivolowitz** [comment]
Thank you for the suggestion. Do you know of any tool that could automate building all this into a PDF? Are you hoping for a single PDF or a PDF per markdown file? We're entering a period of rapid changes expected so I am not sure this is the right time but the time to make PDFs will come.

**Comment by pkivolowitz** [comment]
OK - I can see a way forward on this. It'll take a bit of effort (to do nicely) but I can do it.

**Comment by El-Wumbus** [comment]
HTML generation is also a possibility with mdbook. Then github.io can be used for hosting.

**Comment by pkivolowitz** [comment]
The automatic conversion to PDF is coming soon!

**Comment by cross-hello** [comment]
תודה אתה

Jan 15, 2023 04:44:25 pkivolowitz ***@***.***>:

**Comment by pkivolowitz** [comment]
PDFs there now. In the future they'll be updated regularly.
