### ISSUE TITLE
`ldr` instruction not explained

### ISSUE THREAD

**Issue by 0x3333** [pkivolowitz/asm_book#12]
Here: https://github.com/pkivolowitz/asm_book/blob/main/section_1/hello_world/README.md#lines-7-8-and-9

Assembly line number 7 is not explained:

`    ldr     x0, [x21], 8            // argv++, old value in x0          // 7 `

What the `8` means? I know,but an explanation would be nice for newbies!

**Comment by pkivolowitz** [comment]
Thank you - I have made these changes.
