### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by multitudes** [pkivolowitz/asm_book#23]
Going through the chapter at [ldr.md](https://github.com/pkivolowitz/asm_book/blob/main/section_1/regs/ldr.md) in [Indexing Through An Array of struct](https://github.com/pkivolowitz/asm_book/blob/main/section_1/regs/ldr.md#indexing-through-an-array-of-struct) there is a broken link in the line below saying 
> You should read the chapter on struct found [here](https://github.com/pkivolowitz/asm_book/blob/main/section_1/regs/where?).

I think the readme for the struct page is not yet written :)

**Comment by pkivolowitz** [comment]
The link should lead to the alignment page... it does now. Thank you!
