### ISSUE TITLE
Section 1 - Hello World - stp explanation

### ISSUE THREAD

**Issue by 4rneee** [pkivolowitz/asm_book#24]
In the [explanation of line 3](https://github.com/pkivolowitz/asm_book/blob/main/section_1/hello_world/README.md#line-3-1) of Version 5 of the program. It says:

> In a higher level language `Line 3` would look like this:
> ```c++
> *(--sp) = x21;
> *(--sp) = x30;
> ```
> That is, subtract 8 from the stack pointer and copy `x21` to that location. Then, subtract 8 from the stack pointer and copy `x30` to that location.

Please correct me if I'm wrong, *but*:  
I think this explanation is misleading because it implies that after the instruction `stp   x21, x30, [sp, -16]!` the stack looks like this:  
```text
+-----+
| ... |
+-----+
| x21 |
+-----+
| x30 | <-- sp
+-----+
```
When in reality the value of `x21` is stored at the lower address and the value of `x30` at the higher one.

&nbsp;

On a site note: The same section contains a missing closing bracket https://github.com/pkivolowitz/asm_book/blob/88d0bf495a720d1e739c6bed186069ccc6c494e4/section_1/hello_world/README.md?plain=1#L548

**Comment by pkivolowitz** [comment]
Quite right... please see new text plus the code I used to test (will make for an addition in the variadics chapter) in file stack_order.S in this folder. The confirmation can be viewed in gdb.
