### ISSUE TITLE
Stack issue with SillyFunction

### ISSUE THREAD

**Issue by gitonthescene** [pkivolowitz/asm_book#25]
First, thanks for putting this out there.  It's a very clear read and immensely useful.

It's possible I'm misunderstanding something, but should [this line](https://github.com/pkivolowitz/asm_book/blob/main/section_1/funcs/README2.md?plain=1#L283) be `ldr        x30, [sp], 16` ?

Adding up the increments and decrements to stack in the entire program, it looks like it gets decremented by 16 three times, but incremented by 32 twice.  Perhaps it's [this line](https://github.com/pkivolowitz/asm_book/blob/main/section_1/funcs/README2.md?plain=1#L299) that needs changing.  I'm unclear who is responsible for freeing stack consumed by parameters.  Is it the caller or the callee?

As I say, it's possible I'm missing something entirely here and would appreciate a correction if that's the case.

Regards,

**Comment by pkivolowitz** [comment]
Good catch. The program worked because a bug negated another bug relating to pre/post changes to the stack. 

Whoever changes the stack must undo the changes unless documented otherwise.

Code is corrected now. Correcting the text in a moment.

Thank you!

**Comment by gitonthescene** [comment]
No worries.  Thanks for the quick reply.
