### ISSUE TITLE
2nd literals example format incorrect?

### ISSUE THREAD

**Issue by gitonthescene** [pkivolowitz/asm_book#28]
Just reading through [section_2/float/literals](https://github.com/pkivolowitz/asm_book/blob/main/section_2/float/literals.md) and there is a call to [printf](https://github.com/pkivolowitz/asm_book/blob/main/section_2/float/literals.md?plain=1#L90), but it looks like only registers `x0` and `x2` have been set though the [format](https://github.com/pkivolowitz/asm_book/blob/main/section_2/float/literals.md?plain=1#L99) takes an int and two floats.  Are the two floats `d0` and `d1`?  If so then it's not clear to me by what mechanism they get passed as the third and fourth argument.

Perhaps the [passing arguments](https://github.com/pkivolowitz/asm_book/blob/main/section_1/funcs/README2.md) section could include an example of passing floats?

**Comment by pkivolowitz** [comment]
Lines 19 through 21 put doubles into d0 and d1. printf %f only prints doubles, by the way. That's why the floats are converted to doubles. Note this code is Linux only. Had it been Mac, x1, d0 and d1 would have to be put on the stack. I will amplify the comments about this code.

**Comment by pkivolowitz** [comment]
A bit of amplification added.

**Comment by gitonthescene** [comment]
Thanks.  Part of what confuses me is that in C the floats would be the third and fourth argument which I would have guessed should be `d2` and `d3` rather than `d0` and `d1`.
