### ISSUE TITLE
Please specify license

### ISSUE THREAD

**Issue by cyrilmhansen** [pkivolowitz/asm_book#7]
Would https://creativecommons.org/licenses/by-sa/4.0/ suit your goals ?

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by pkivolowitz** [comment]
Done.
